groups:
  - name: devs # name of the group
    reviewers: 2 # how many reviewers do you want to assign?
    internal_reviewers: 2 # how many reviewers do you want to assign when the PR author belongs to this group?
    usernames: # github usernames of the reviewers
      - ivanchaban
      - aleksandrew
      - alexandr-feschenko
      - nikita-parkhomenko
      - SunRise-afk
      - serejabogdan
